
[llm.presets]

llm_for_writing_analysis = { model = "base-claude", temperature = 0.2 }
llm_for_social_post_writing = { model = "base-claude", temperature = 0.9 }

llm_for_data_synthesis = { model = "gpt-4o-mini", temperature = 0.9 }
llm_to_enrich = { model = "base-claude", temperature = 0.1 }
llm_to_answer = { model = "base-claude", temperature = 0.1 }
