// Generated by `make render` from methods/advisory_board/ and cookbook.toml, as the TypeScript snippet of methods/advisory_board/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/advisory_board@v0.18.0",
  inputs: {
    user_input: "We're a mid-stage B2B SaaS company (50 employees, $5M ARR) facing declining customer retention. Our churn rate has increased from 8% to 15% annually over the past 6 months.\n\nKey challenges:\n- Customer onboarding takes 4-6 weeks (industry average is 2-3 weeks)\n- Support response time averages 24 hours\n- Feature adoption is low - only 30% of customers use our advanced features\n- Competition from 3 new entrants with better UX\n\nOur goal is to reduce churn to under 10% within 6 months while maintaining growth targets.\nWe have a budget of $500K and need to prioritize initiatives that will have the biggest impact.\n\nCurrent team: 8 engineers, 4 sales, 3 marketing, 2 customer success, 5 operations.\nKey stakeholders: CEO, VP Product, VP Sales, Head of Customer Success.",
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/advisory_board/, so that tsc holds the page's call to the concept its "Returns" line names.
import { parseMarkdownReport } from "./generated/advisory_board/binder";

const output = parseMarkdownReport(result.main_stuff);
