"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import List, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.wip.discord_newsletter.structures.discord_newsletter__discord_message import discord_newsletter__DiscordMessage


class discord_newsletter__DiscordChannelUpdate(StructuredContent):
    """A Discord channel with its messages for newsletter generation"""

    name: str = Field(..., description="Name of the Discord channel")
    position: int = Field(..., description="Position of the channel")
    messages: Optional[List[discord_newsletter__DiscordMessage]] = Field(default=None, description="List of messages in the channel")
