"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import List, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.wip.discord_newsletter.structures.discord_newsletter__attachment import discord_newsletter__Attachment
from examples.wip.discord_newsletter.structures.discord_newsletter__embed import discord_newsletter__Embed


class discord_newsletter__DiscordMessage(StructuredContent):
    """A Discord message within a channel"""

    author: str = Field(..., description="Author of the message")
    content: str = Field(..., description="Content of the message")
    attachments: Optional[List[discord_newsletter__Attachment]] = Field(default=None, description="List of message attachments")
    embeds: Optional[List[discord_newsletter__Embed]] = Field(default=None, description="List of message embeds")
    link: str = Field(..., description="Link to the message")
