"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class discord_newsletter__ChannelSummary(StructuredContent):
    """A summarized Discord channel for newsletter inclusion"""

    channel_name: str = Field(..., description="Name of the Discord channel")
    position: int = Field(..., description="Position of the channel for ordering")
    summary_items: Optional[List[str]] = Field(default=None, description="Well-written summaries of the channel's activity")
    category: Optional[Literal["Share", "Introduce Yourself", "Geographic Hubs", "Other"]] = Field(
        default=None, description="Category of the channel"
    )
