"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from examples.wip.discord_newsletter.structures.discord_newsletter__attachment import Attachment
from examples.wip.discord_newsletter.structures.discord_newsletter__embed import Embed
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class DiscordMessage(StructuredContent):
    """A Discord message within a channel"""

    author: str = Field(..., description="Author of the message")
    content: str = Field(..., description="Content of the message")
    attachments: List[Attachment] = Field(..., description="List of message attachments")
    embeds: List[Embed] = Field(..., description="List of message embeds")
    link: str = Field(..., description="Link to the message")
