"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class ReceiptMatchCheck(StructuredContent):
    """LLM assessment of whether receipt matches the expense details"""

    is_matching: bool = Field(..., description="Whether receipt matches expense")
    merchant_matches: bool = Field(..., description="Merchant name matches")
    amount_matches: bool = Field(..., description="Amount matches")
    date_matches: bool = Field(..., description="Date matches")
    confidence: Literal["high", "medium", "low"] = Field(..., description="Confidence level")
    discrepancies: Optional[str] = Field(default=None, description="Description of any discrepancies found")
