"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from datetime import datetime
from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class expense_validator__Expense(StructuredContent):
    """A single expense line item from the expense report"""

    expense_id: str = Field(..., description="Unique expense identifier (e.g., EXP-20260115-0001)")
    expense_date: datetime = Field(..., description="Date of the expense")
    category: Literal[
        "supermarket", "restaurant", "cafe", "hotel", "airline", "office_supplies", "pharmacy", "electronics", "gas_station", "delivery", "other"
    ] = Field(..., description="Expense category")
    merchant: str = Field(..., description="Merchant or vendor name")
    total_amount: float = Field(..., description="Total expense amount")
    currency: str = Field(..., description="Currency code (e.g., USD)")
    business_purpose: str = Field(..., description="Business justification for the expense")
