"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class SpendingLimitCheck(StructuredContent):
    """Check if expense is within spending limits based on employee seniority and expense category"""

    expense_id: str = Field(..., description="The expense ID being checked")
    within_limit: bool = Field(..., description="Whether expense is within the allowed limit")
    limit_amount: float = Field(..., description="The spending limit for this seniority/category")
    claimed_amount: float = Field(..., description="The amount claimed")
    exceeded_by: float = Field(..., description="Amount exceeded (0 if within limit)")
    category: str = Field(..., description="The expense category checked")
    seniority: str = Field(..., description="The employee seniority level")
