"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class expense_validator__PurposeQualityCheck(StructuredContent):
    """LLM assessment of whether the business purpose justification is adequate and professional"""

    expense_id: str = Field(..., description="The expense ID being checked")
    is_adequate: bool = Field(..., description="Whether the business purpose is adequately justified")
    clarity_score: Literal["excellent", "good", "acceptable", "insufficient", "missing"] = Field(..., description="Clarity of the justification")
    business_relevance: Literal["clearly_related", "possibly_related", "unclear", "unrelated"] = Field(
        ..., description="How clearly the expense relates to business activities"
    )
    recommendation: Literal["approve", "approve_with_note", "request_clarification", "reject"] = Field(
        ..., description="Recommendation for the expense"
    )
    assessment: str = Field(..., description="Detailed explanation of the assessment")
