"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import List

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.wip.validate_expense_data.structures.expense_validator__employee import Employee
from examples.wip.validate_expense_data.structures.expense_validator__expense import Expense


class ExpenseReport(StructuredContent):
    """Complete parsed expense report with employee and all expenses"""

    employee: Employee = Field(..., description="The employee who submitted the report")
    expenses: List[Expense] = Field(..., description="List of expenses from the report")
