"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from examples.c_advanced.validate_expense_data.structures.expense_validator__expense import Expense
from examples.c_advanced.validate_expense_data.structures.expense_validator__receipt import Receipt
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class ExpenseWithReceipt(StructuredContent):
    """An expense paired with its receipt image"""

    expense: Expense = Field(..., description="The expense details")
    receipt: Receipt = Field(..., description="The receipt image")
