"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class DuplicateCheck(StructuredContent):
    """Check for potential duplicate expenses"""

    is_duplicate: bool = Field(..., description="Whether this appears to be a duplicate")
    similar_expense_id: Optional[str] = Field(default=None, description="ID of similar expense if found")
    similarity_reason: Optional[str] = Field(default=None, description="Why it might be a duplicate")
