"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class ReasonableAmountCheck(StructuredContent):
    """LLM assessment of whether expense amount is reasonable for the category and context"""

    expense_id: str = Field(..., description="The expense ID being checked")
    is_reasonable: bool = Field(..., description="Whether the amount seems reasonable")
    expected_range_min: float = Field(..., description="Lower bound of expected price range")
    expected_range_max: float = Field(..., description="Upper bound of expected price range")
    variance_category: Literal["within_range", "slightly_high", "significantly_high", "slightly_low", "significantly_low"] = Field(
        ..., description="How the amount compares to expectations"
    )
    assessment: str = Field(..., description="Explanation of the assessment")
