"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class ReceiptMatchCheck(StructuredContent):
    """Vision LLM assessment of whether receipt matches the expense details"""

    expense_id: str = Field(..., description="The expense ID being checked")
    has_receipt: bool = Field(..., description="Whether a receipt was provided for this expense")
    is_matching: bool = Field(..., description="Whether receipt matches expense (false if no receipt)")
    extracted_merchant: str = Field(..., description="Merchant name extracted from the receipt image")
    merchant_matches: bool = Field(..., description="Merchant name on receipt matches claimed merchant")
    amount_matches: bool = Field(..., description="Amount on receipt matches claimed amount")
    date_matches: bool = Field(..., description="Date on receipt matches claimed date")
    confidence: Literal['high', 'medium', 'low'] = Field(..., description="Confidence level of the assessment")
    discrepancies: Optional[str] = Field(default=None, description="Description of any discrepancies found")
