"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class TimelinesCheck(StructuredContent):
    """Check if expense was submitted within the allowed timeframe (30 days from expense date)"""

    expense_id: str = Field(..., description="The expense ID being checked")
    is_timely: bool = Field(..., description="Whether the expense was submitted within deadline")
    days_since_expense: int = Field(..., description="Number of days since the expense occurred")
    submission_deadline: int = Field(..., description="Maximum allowed days for submission")
    policy_status: Literal['compliant', 'late_but_acceptable', 'too_late'] = Field(..., description="Policy compliance status")
    message: str = Field(..., description="Explanation of the timeliness status")
