"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from examples.wip.validate_expense_data.structures.expense_validator__employee import Employee
from examples.wip.validate_expense_data.structures.expense_validator__expense_validation_result import ExpenseValidationResult
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class ValidationReport(StructuredContent):
    """Final validation report with all expense results and executive summary"""

    employee: Employee = Field(..., description="The employee who submitted the report")
    expense_results: List[ExpenseValidationResult] = Field(..., description="Validation results for each expense")
    total_claimed: float = Field(..., description="Total amount claimed")
    total_approved: float = Field(..., description="Total amount approved for reimbursement")
    total_rejected: float = Field(..., description="Total amount rejected")
    total_pending: float = Field(..., description="Total amount pending clarification")
    approval_rate: float = Field(..., description="Percentage of expenses fully approved")
    expenses_approved: int = Field(..., description="Number of expenses approved")
    expenses_rejected: int = Field(..., description="Number of expenses rejected")
    expenses_pending: int = Field(..., description="Number of expenses pending clarification")
    summary_notes: str = Field(..., description="Executive summary notes for the finance team")
