"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import List

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.wip.validate_expense_data.structures.expense_validator__employee import expense_validator__Employee
from examples.wip.validate_expense_data.structures.expense_validator__expense import expense_validator__Expense


class expense_validator__ExpenseReport(StructuredContent):
    """Complete parsed expense report with employee and all expenses"""

    employee: expense_validator__Employee = Field(..., description="The employee who submitted the report")
    expenses: List[expense_validator__Expense] = Field(..., description="List of expenses from the report")
