"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class SpendingLimitCheck(StructuredContent):
    """Check if expense is within spending limits for seniority level"""

    within_limit: bool = Field(..., description="Whether expense is within limit")
    limit_amount: float = Field(..., description="The applicable spending limit")
    exceeded_by: float = Field(..., description="Amount exceeded (0 if within limit)")
    category: str = Field(..., description="Expense category")
    seniority: str = Field(..., description="Employee seniority level")
