"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class WeekendCheck(StructuredContent):
    """Check if expense occurred on a weekend (company policy: no weekend expenses without prior approval)"""

    expense_id: str = Field(..., description="The expense ID being checked")
    is_weekday: bool = Field(..., description="True if expense is on a weekday (Mon-Fri)")
    day_of_week: str = Field(..., description="Day name (Monday, Tuesday, etc.)")
    policy_status: Literal['compliant', 'requires_approval', 'violation'] = Field(..., description="Policy compliance status")
    message: str = Field(..., description="Explanation of the check result")
