"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class SuspiciousPatternCheck(StructuredContent):
    """Detection of suspicious expense patterns"""

    is_suspicious: bool = Field(..., description="Whether suspicious patterns detected")
    patterns_found: Optional[List[str]] = Field(default=None, description="List of suspicious patterns identified")
    risk_level: Literal["none", "low", "medium", "high"] = Field(..., description="Risk assessment")
