"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class RuleViolation(StructuredContent):
    """A specific rule violation found during validation"""

    rule_code: str = Field(..., description="Unique code for the rule")
    rule_name: str = Field(..., description="Human-readable rule name")
    severity: Literal["warning", "rejection"] = Field(..., description="Severity level")
    message: str = Field(..., description="Detailed explanation of the violation")
