"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from examples.c_advanced.gen_expense_data.structures.expense_data_generation__purchased_item import PurchasedItem
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class ReceiptItemsAndTotals(StructuredContent):
    """Items purchased and calculated totals for a receipt"""

    items: Optional[List[PurchasedItem]] = Field(default=None, description="List of purchased items")
    subtotal: float = Field(..., description="Sum of all line totals")
    tax_rate: float = Field(..., description="Tax rate as decimal (e.g., 0.08 for 8%)")
    tax_amount: float = Field(..., description="Calculated tax amount")
    total_amount: float = Field(..., description="Final total (subtotal + tax)")
    currency: str = Field(..., description="Currency code (always USD)")
