"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class CompanyCategory(StructuredContent):
    """A type of company for expense generation with typical expense range"""

    category: Literal['supermarket', 'restaurant', 'cafe', 'hotel', 'airline', 'office_supplies', 'pharmacy', 'electronics', 'gas_station', 'delivery'] = Field(..., description="Company category type")
    typical_expense_range: str = Field(..., description="Typical expense range e.g. '20-80 USD'")
