"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class expense_data_generation__Employee(StructuredContent):
    """An employee who can submit expense reports"""

    employee_id: str = Field(..., description="Unique employee identifier")
    full_name: str = Field(..., description="Employee full name")
    email: str = Field(..., description="Employee email address")
    department: str = Field(..., description="Department name")
    job_title: str = Field(..., description="Job title")
    seniority: Literal["Junior", "Senior", "Lead", "Manager", "Director", "VP", "Executive"] = Field(..., description="Employee seniority level")
