"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.c_advanced.gen_expense_data.structures.expense_data_generation__expense_scenario import expense_data_generation__ExpenseScenario


class expense_data_generation__CompanyCategory(StructuredContent):
    """A type of company for expense generation with typical expense range"""

    category: Literal[
        "supermarket",
        "restaurant",
        "cafe",
        "hotel",
        "airline",
        "office_supplies",
        "pharmacy",
        "electronics",
        "gas_station",
        "delivery",
        "bowling_alley",
        "streaming_service",
        "gaming_store",
        "movie_theater",
        "spa",
        "gym",
        "liquor_store",
        "nightclub",
    ] = Field(..., description="Company category type")
    typical_expense_range: str = Field(..., description="Typical expense range e.g. '20-80 USD'")
    expense_scenario: expense_data_generation__ExpenseScenario = Field(..., description="The fraud scenario for this expense")
