"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pipelex.core.stuffs.html_content import HtmlContent
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.c_advanced.gen_expense_data.structures.expense_data_generation__employee import Employee
from examples.c_advanced.gen_expense_data.structures.expense_data_generation__expense_with_receipt import ExpenseWithReceipt


class EmployeeExpenseReport(StructuredContent):
    """An employee with their list of expenses, receipts, and HTML report"""

    employee: Employee = Field(..., description="The employee")
    expenses_with_receipts: List[ExpenseWithReceipt] = Field(..., description="List of expenses with receipts")
    html_report: HtmlContent = Field(..., description="HTML formatted expense report")
