"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from datetime import datetime

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class expense_data_generation__ReceiptHeader(StructuredContent):
    """Header information for a receipt"""

    transaction_number: str = Field(..., description="Transaction/ticket number (format: TIC# XXXXX)")
    transaction_date: datetime = Field(..., description="Date of transaction (must be in January 2026)")
    transaction_time: str = Field(..., description="Time of transaction (format: HH:MM AM/PM)")
