"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from examples.c_advanced.gen_expense_data.structures.expense_validator__employee import Employee
from examples.c_advanced.gen_expense_data.structures.expense_validator__expense_with_receipt import ExpenseWithReceipt
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class ExpenseReport(StructuredContent):
    """Complete expense report extracted from PDF"""

    employee: Employee = Field(..., description="The employee")
    expenses_with_receipts: List[ExpenseWithReceipt] = Field(..., description="List of expenses with receipts")
