"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class expense_data_generation__PurchasedItem(StructuredContent):
    """An item purchased on a receipt"""

    name: str = Field(..., description="Item name from catalog")
    quantity: int = Field(..., description="Quantity purchased")
    unit_price: float = Field(..., description="Price per unit")
    line_total: float = Field(..., description="Total for this line (quantity * unit_price)")
    currency: str = Field(..., description="Currency code (always USD)")
