"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class CompanyProfile(StructuredContent):
    """A company with its details and product catalog"""

    name: str = Field(..., description="Company name")
    category: str = Field(..., description="Company category type")
    address: str = Field(..., description="Street address")
    city: str = Field(..., description="City name")
    postal_code: str = Field(..., description="Postal/ZIP code")
    country: str = Field(..., description="Country name")
    phone: str = Field(..., description="Phone number")
    website: Optional[str] = Field(default=None, description="Website URL")
    tax_id: Optional[str] = Field(default=None, description="Tax identification number")
    product_catalog: str = Field(..., description="List of products/services with typical prices")
