"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field

from examples.c_advanced.gen_expense_data.structures.expense_data_generation__expense import Expense
from examples.c_advanced.gen_expense_data.structures.expense_data_generation__receipt import Receipt


class ExpenseWithReceipt(StructuredContent):
    """An expense paired with its receipt image"""

    expense: Expense = Field(..., description="The expense details")
    receipt: Optional[Receipt] = Field(default=None, description="The receipt image")
