"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class ReceiptContent(StructuredContent):
    """The full text content of a receipt with metadata"""

    full_receipt_text: str = Field(..., description="Complete formatted receipt text including header, items, totals")
    total_amount: float = Field(..., description="Total amount on the receipt")
    currency: str = Field(..., description="Currency code")
    expense_date: datetime = Field(..., description="Date of the transaction")
    business_purpose: str = Field(..., description="Business justification for the expense")
