"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class DateValidityCheck(StructuredContent):
    """Result of checking date validity"""

    is_valid: bool = Field(..., description="Whether date is valid for reimbursement")
    days_old: int = Field(..., description="Number of days since expense date")
    max_days_allowed: int = Field(..., description="Maximum days allowed for submission")
    reason: Optional[str] = Field(default=None, description="Explanation if invalid")
