# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "httpx>=0.25", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/review_nda/ and cookbook.toml, as the Python snippet of methods/review_nda/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

import httpx
from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    inputs = httpx.get("https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.20.3/methods/review_nda/inputs.json").json()
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/review_nda@v0.20.3",
            inputs=inputs,
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/review_nda/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
# pipe's declared output, so the type checker fails when the page names a concept those types no longer hold.
from pipelex_sdk.runs import RunResults

from generated.review_nda.models import NdaReview


def read_output(result: RunResults) -> NdaReview:
    """The method returns one `NdaReview`."""
    return NdaReview.model_validate(result.main_stuff)
