// Generated by `make render` from methods/gen_expense_data/ and cookbook.toml, as the TypeScript snippet of methods/gen_expense_data/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/gen_expense_data@v0.18.0",
  inputs: {
    nb_employees: {
      number: 2,
    },
  },
});
console.log(result.main_stuff);
