// Generated by `make render` from methods/extract_gantt/ and cookbook.toml, as the TypeScript snippet of methods/extract_gantt/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/extract_gantt@v0.18.0",
  inputs: {
    gantt_chart_image: {
      url: "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_gantt/gantt_tree_house.png",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/extract_gantt/, so that tsc holds the page's call to the concept its "Returns" line names.
import { parseGanttChart } from "./generated/extract_gantt/binder";

const output = parseGanttChart(result.main_stuff);
