"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class StructuredSummary(StructuredContent):
    """Generated StructuredSummary class"""

    summary: str = Field(..., description="Summary of the text, super clear and factual")
    abstract: str = Field(..., description="Abstract of the summary 1 short sentences")
    main_concepts: List[str] = Field(..., description="Array of main concepts tackled in the text")
