// Generated by `make render` from methods/extract_slides/ and cookbook.toml, as the TypeScript snippet of methods/extract_slides/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/extract_slides@v0.18.0",
  inputs: {
    document: {
      url: "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/presentations/CatOps.pdf",
    },
  },
});
console.log(result.main_stuff);
