# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "httpx>=0.25"]
# ///
# Generated by `make render` from methods/discord_newsletter/ and cookbook.toml, as the Python snippet of methods/discord_newsletter/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

import httpx
from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    inputs = httpx.get("https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.18.0/methods/discord_newsletter/inputs.json").json()
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/discord_newsletter@v0.18.0",
            inputs=inputs,
        )
        print(result.main_stuff)


asyncio.run(main())
