# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "httpx>=0.25", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/discord_newsletter/ and cookbook.toml, as the Python snippet of methods/discord_newsletter/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

import httpx
from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    inputs = httpx.get("https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.18.0/methods/discord_newsletter/inputs.json").json()
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/discord_newsletter@v0.18.0",
            inputs=inputs,
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/discord_newsletter/, so that the type checker holds the page's call to the concept its "Returns" line names.
from pipelex_sdk.runs import RunResults

from generated.discord_newsletter.models import HtmlNewsletter


def read_output(result: RunResults) -> HtmlNewsletter:
    """The method returns one `HtmlNewsletter`."""
    return HtmlNewsletter.model_validate(result.main_stuff)
