# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/gen_expense_data/ and cookbook.toml, as the Python snippet of methods/gen_expense_data/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/gen_expense_data@v0.19.1",
            inputs={
                "nb_employees": {
                    "number": 2,
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/gen_expense_data/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
# pipe's declared output, so the type checker fails when the page names a concept those types no longer hold.
from pipelex_sdk.runs import RunResults
from pydantic import BaseModel, TypeAdapter

from generated.gen_expense_data.models import EmployeeExpenseReport


class EmployeeExpenseReportList(BaseModel):
    """The envelope `{"items": [...]}` the SDK documents for a list output."""

    items: list[EmployeeExpenseReport]


def read_output(result: RunResults) -> list[EmployeeExpenseReport]:
    """The method returns a list of `EmployeeExpenseReport`, which the SDK documents as the envelope and the hosted API answers as a bare list today."""
    output = TypeAdapter[list[EmployeeExpenseReport] | EmployeeExpenseReportList](list[EmployeeExpenseReport] | EmployeeExpenseReportList).validate_python(result.main_stuff)
    return output.items if isinstance(output, EmployeeExpenseReportList) else output
