domain = "power_extractor"
definition = "The domain for power extractor"


[pipe.write_markdown_from_page_content]
PipeLLM = "Write markdown from page content"
input = "documents.PageContent"
output = "TextContent"
images = ["page_content.screenshot"]
system_prompt = """You are multimodal LLM, expert at converting images into perfect markdown."""
prompt_template = """
You are given an image which is a screenshot of a page of a document.
You are also given the text extracted from the page by an OCR model.
Your task is to output the perfect markdown of the page.

Here is the text extracted from the page:
@page_content.text_and_images.text

- Make sure you do not miss any information from the page.
- Output only the markdown, nothing else. No need for "```markdown" or "```".
- Make sure latex is rendered correctly.
"""

[pipe.power_markdown_extractor]
PipeSequence = "Update page content with markdown"
input = "documents.PageContent"
output = "TextContent"
steps = [
    { pipe = "extract_page_contents_from_pdf", result = "page_content" },
    { pipe = "write_markdown_from_page_content", batch_as = "page_content", result = "markdown" },
]
