// Generated by `make render` from methods/extract_dpe/ and cookbook.toml, as the TypeScript snippet of methods/extract_dpe/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/extract_dpe@v0.19.1",
  inputs: {
    document: {
      url: "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_dpe/dpe_single_page.pdf",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/extract_dpe/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
// pipe's declared output, so tsc fails when the page names a concept those types no longer hold.
import { parseDpe } from "./generated/extract_dpe/binder";

const output = parseDpe(result.main_stuff);
