import json
import re
from pathlib import Path

import pytest
from pydantic import JsonValue

from scripts.cookbook import load_cookbook
from scripts.exceptions import CookbookLayoutError
from scripts.recipes import find_trees, recipe_problems
from scripts.render import (
    INLINE_INPUTS_LIMIT,
    python_literal,
    render_all,
    render_front_page,
    render_pages,
    render_snippets,
    type_phrase,
    typescript_literal,
)
from scripts.views import OUTPUT_FOLD_LINES
from tests.tooling.test_data import (
    WIDGETS_OUTPUT,
    WIDGETS_SAMPLE_URL,
    WIDGETS_SOURCE,
    WORDS_BUNDLE,
    WORDS_CONTRACT,
    MakeCookbook,
    add_words_synthetic_record,
    make_widgets_sample_synthetic,
    write_snapshot,
)

# Each snippet file, by its path under `tests/snippets/<name>/`, with the fence its block has on the page and the prefix of its comment lines.
SNIPPET_FILES = {"typescript/snippet.ts": ("ts", "//"), "python/snippet.py": ("python", "#")}
# Each generated tree's sidecar, by its path under `tests/snippets/<name>/`, `{name}` standing for the method's, with the target it names.
SIDECARS = {"typescript/generated/{name}/sources.json": "ts-zod", "python/generated/{name}/sources.json": "python-pydantic"}


def _fenced_block(page: str, *, language: str) -> str:
    """The body of the page's one code block fenced as `language`, up to and including its last newline."""
    blocks: list[str] = re.findall(rf"^```{language}\n(.*?)^```$", page, flags=re.MULTILINE | re.DOTALL)
    [block] = blocks
    return block


def _split_snippet(snippet: str, *, block: str) -> tuple[str, str]:
    """The lines of a snippet file above the page's block and those below it, once the block is found in the file verbatim."""
    header, found, typed_read = snippet.partition(block)
    assert found, "the page's snippet is not in the file verbatim"
    return header, typed_read


def _snippet_files(root: Path, name: str) -> tuple[Path, Path]:
    """The TypeScript and Python snippet files of a method."""
    return root / "tests" / "snippets" / name / "typescript" / "snippet.ts", root / "tests" / "snippets" / name / "python" / "snippet.py"


class TestRender:
    def test_page_is_rendered_from_the_package_and_its_editorial_entry(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        pages = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)
        page = pages[root / "methods" / "extract_widgets" / "README.md"]

        address = "github.com/Pipelex/pipelex-cookbook/extract_widgets@v0.9.0"
        assert page.startswith("<!-- Generated by `make render` from methods/extract_widgets/")
        assert "# Widget extraction\n\nRead a catalogue page and list every widget on it.\n" in page
        assert f"`{address}` · [bundle.mthds](bundle.mthds) · [sample catalogue]({WIDGETS_SAMPLE_URL})" in page
        assert "**Takes** `catalogue`, an image (`CataloguePage`): A page of a widget catalogue." in page
        assert "**Returns** a `WidgetList`: Every widget on the page." in page
        assert "- `widgets`, a list of `Widget`: The widgets, in page order." in page
        assert f"```text\nRun {address} on {WIDGETS_SAMPLE_URL}\n```" in page
        assert "In ChatGPT you can attach your own file instead of the link" in page
        assert f'  method_ref: "{address}",' in page
        assert f"npm create @pipelex/method-app@latest widgets-app -- --method {address}" in page
        assert f"```text\nCopy {address} into ./widgets, add each widget's price to what it extracts, prove it" in page
        # The page is about using the method: the skills the agent chains stay off it, and with no snapshot yet it has no "What you get".
        assert "What you get" not in page
        assert "/pipelex-catalog" not in page

    def test_the_page_shows_the_sample_then_what_it_returned_then_its_contract_then_the_doors(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook(with_sample=True)
        write_snapshot(root, "extract_widgets", output=WIDGETS_OUTPUT)
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "extract_widgets" / "README.md"]

        order = ["# Widget extraction", "`github.com/Pipelex/pipelex-cookbook/extract_widgets@v0.9.0`", "## The sample", "## What you get"]
        order += ["**Takes**", "**Returns**", "## Try it in your chatbot", "## Put it in your code", "## Run it on your own machine"]
        positions = [page.index(marker) for marker in order]
        assert positions == sorted(positions)
        assert (
            "## The sample\n\n![sample catalogue](../../assets/extract_widgets/catalogue.png)\n\n"
            f"*From [{WIDGETS_SOURCE}]({WIDGETS_SOURCE}), copied on 2026-09-20. Cut to its first page.* "
            "Licence: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/). Credit: The Widget Society.\n\n## What you get\n\n"
        ) in page
        assert (
            "Run on production on 28 September 2026, from the package's files, in 37 seconds. This is what it returned:\n\n"
            "**`widgets`**\n\n| `name` | `colour` |\n|---|---|\n| Sprocket | red |\n| Flange | blue |\n\n**Takes**"
        ) in page

    def test_a_method_without_a_snapshot_gets_its_page_without_what_you_get(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook(with_sample=True)
        make_widgets_sample_synthetic(root)
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "extract_widgets" / "README.md"]
        assert "## What you get" not in page
        assert (
            "![sample catalogue](../../assets/extract_widgets/catalogue.png)\n\n*Fictional, made for this example.* "
            "Licence: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/). Credit: The Widget Society.\n\n**Takes**"
        ) in page

    def test_an_inline_sample_made_up_for_the_example_says_it_was_written_for_it(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        add_words_synthetic_record(root)
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "count_words" / "README.md"]
        assert (
            "## The sample\n\n> The quick brown fox\n\n*Written for this example.* "
            "Licence: [MIT](https://github.com/Pipelex/pipelex-cookbook/blob/main/LICENSE). Credit: Evotis S.A.S.\n\n**Takes**"
        ) in page
        assert "Fictional" not in page

    def test_a_long_output_is_folded_whole_under_its_name_below_the_runs_line(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook(with_sample=True)
        widgets: JsonValue = [{"name": f"Widget {index}", "colour": "red"} for index in range(OUTPUT_FOLD_LINES)]
        write_snapshot(root, "extract_widgets", output={"widgets": widgets})
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "extract_widgets" / "README.md"]
        # GitHub renders the Markdown inside a `<details>` block only after a blank line following its `</summary>`.
        assert (
            "This is what it returned:\n\n<details>\n<summary>The widget list</summary>\n\n"
            "**`widgets`**\n\n| `name` | `colour` |\n|---|---|\n| Widget 0 | red |\n"
        ) in page
        assert f"| Widget {OUTPUT_FOLD_LINES - 1} | red |\n\n</details>\n\n**Takes**" in page

    def test_a_sample_without_its_record_is_shown_without_a_credit_line(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "count_words" / "README.md"]
        assert "## The sample\n\n> The quick brown fox\n\n**Takes**" in page

    def test_several_inputs_are_each_named(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        (root / "methods" / "count_words" / "inputs.json").write_text('{"text": "The quick brown fox", "language": "en"}', encoding="utf-8")
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "count_words" / "README.md"]
        assert "## The sample\n\n**Sample text**\n\n> The quick brown fox\n\n**Sample language**\n\n> en\n\n**Takes**" in page

    def test_page_without_an_editorial_entry_comes_from_the_manifest(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        pages = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)
        page = pages[root / "methods" / "count_words" / "README.md"]

        address = "github.com/Pipelex/pipelex-cookbook/count_words@v0.9.0"
        inputs_url = "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.9.0/methods/count_words/inputs.json"
        assert "# Word Count\n\nCount the words of a text.\n" in page
        assert f"`{address}` · [bundle.mthds](bundle.mthds)\n" in page
        assert "**Takes** `text`, a text (`Text`)." in page
        # A native concept's description only restates its type, so the Returns line stops at the concept.
        assert "**Returns** a `Text`.\n" in page
        assert f"```text\nRun {address} with the sample inputs in {inputs_url}\n```" in page
        assert "attach your own file" not in page
        assert f"npm create @pipelex/method-app@latest count-words-app -- --method {address}" in page
        assert f"Copy {address} into ./count_words, adapt what it does to my case, prove it" in page
        assert f"curl -sLo inputs.json {inputs_url}" in page
        assert 'inputs={\n                "text": "The quick brown fox",\n            },' in page

    def test_the_front_page_lists_every_method_and_keeps_its_own_lines(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        front_page = render_front_page(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "README.md"]

        assert front_page.startswith("# Fixture cookbook\n\nWritten by hand.\n\n<!-- BEGIN methods")
        assert "<!-- END methods -->\n\nBetween the lists, written by hand.\n\n<!-- BEGIN library" in front_page
        assert front_page.endswith("<!-- END library -->\n\n## Also written by hand\n")
        assert "- **[Word Count](methods/count_words/)**: Count the words of a text.\n" in front_page
        assert "- **[Widget extraction](methods/extract_widgets/)**: Read a catalogue page and list every widget on it.\n" in front_page

    def test_a_second_render_of_the_front_page_changes_nothing(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        cookbook = load_cookbook(root)
        for path, contents in render_all(cookbook=cookbook, templates_dir=templates_dir).items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf-8")
        assert render_front_page(cookbook=cookbook, templates_dir=templates_dir)[root / "README.md"] == (root / "README.md").read_text(
            encoding="utf-8"
        )

    def test_a_front_page_without_its_region_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        (root / "README.md").write_text("# Fixture cookbook\n", encoding="utf-8")
        with pytest.raises(CookbookLayoutError, match="must hold one region for the list of methods"):
            render_all(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_a_front_page_whose_regions_overlap_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        front_page = root / "README.md"
        methods_end = "<!-- END methods -->\n"
        overlapping = (
            front_page.read_text(encoding="utf-8").replace(methods_end, "").replace("<!-- END library -->", methods_end + "<!-- END library -->")
        )
        front_page.write_text(overlapping, encoding="utf-8")
        with pytest.raises(
            CookbookLayoutError, match="opens the region for the list of the library's methods inside the region for the list of methods"
        ):
            render_all(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_the_tag_is_v_and_the_version_file(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook(version="1.2.3")
        pages = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)
        for page in pages.values():
            assert "@v1.2.3" in page
            assert "@v0.9.0" not in page

    def test_a_package_without_a_contract_snapshot_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        (root / "methods" / "count_words" / "contract.json").unlink()
        with pytest.raises(CookbookLayoutError, match="run `make refresh`"):
            render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_a_chatbot_sentence_that_does_not_format_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        settings_path = root / "cookbook.toml"
        settings_path.write_text(
            settings_path.read_text(encoding="utf-8").replace(
                'app_dir = "widgets-app"', 'chatbot = "Run {address} on {samples"\napp_dir = "widgets-app"'
            ),
            encoding="utf-8",
        )
        with pytest.raises(CookbookLayoutError, match="does not format"):
            render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_only_an_exact_concept_wrapper_is_unwrapped_in_the_snippets(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        inputs_path = root / "methods" / "count_words" / "inputs.json"
        inputs_path.write_text('{"text": {"title": "Fox", "content": "The quick brown fox"}}', encoding="utf-8")
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "count_words" / "README.md"]
        assert '"title": "Fox"' in page

    def test_an_input_holding_a_list_of_files_links_each_one(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        first, second = "https://example.com/a.png", "https://example.com/b.png"
        inputs_path = root / "methods" / "extract_widgets" / "inputs.json"
        inputs_path.write_text(f'{{"catalogue": [{{"url": "{first}"}}, {{"url": "{second}"}}]}}', encoding="utf-8")
        make_widgets_sample_synthetic(root)
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "extract_widgets" / "README.md"]
        assert f"[sample catalogue 1]({first}) · [sample catalogue 2]({second})" in page
        assert f"on {first} and {second}" in page

    def test_each_snippet_file_is_the_pages_snippet_under_comment_lines_then_a_typed_read(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        cookbook = load_cookbook(root)
        pages = render_pages(cookbook=cookbook, templates_dir=templates_dir)
        snippets = render_snippets(cookbook=cookbook, templates_dir=templates_dir)
        assert sorted(snippets) == sorted(
            root / "tests" / "snippets" / name / relative_path.format(name=name)
            for name in ("count_words", "extract_widgets")
            for relative_path in [*SNIPPET_FILES, *SIDECARS]
        )
        for name in ("count_words", "extract_widgets"):
            page = pages[root / "methods" / name / "README.md"]
            for relative_path, (language, comment) in SNIPPET_FILES.items():
                snippet = snippets[root / "tests" / "snippets" / name / relative_path]
                block = _fenced_block(page, language=language)
                assert f"github.com/Pipelex/pipelex-cookbook/{name}@v0.9.0" in block
                header, typed_read = _split_snippet(snippet, block=block)
                assert header.endswith("never edit this file by hand.\n")
                assert all(line.startswith(comment) for line in header.splitlines())
                # A blank line, two in Python, sets the typed read apart from the page's snippet.
                assert typed_read.startswith("\n")
                assert typed_read.lstrip("\n").startswith(f"{comment} Not on the page: the output read through the types `make refresh` generates")
                assert block not in typed_read

    def test_the_typed_read_never_reaches_the_page(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        for page in render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir).values():
            assert "Not on the page" not in page
            assert "read_output" not in page
            assert "/binder" not in page
            assert "RunResults" not in page

    @pytest.mark.parametrize(
        ("name", "concept"),
        [("extract_widgets", "WidgetList"), ("count_words", "Text")],
    )
    def test_the_typed_read_parses_the_output_concept_the_returns_line_names(
        self, make_cookbook: MakeCookbook, templates_dir: Path, name: str, concept: str
    ):
        root = make_cookbook()
        cookbook = load_cookbook(root)
        page = render_pages(cookbook=cookbook, templates_dir=templates_dir)[root / "methods" / name / "README.md"]
        snippets = render_snippets(cookbook=cookbook, templates_dir=templates_dir)
        typescript_path, python_path = _snippet_files(root, name)

        assert f"**Returns** a `{concept}`" in page
        assert snippets[typescript_path].endswith(
            f'import {{ parse{concept} }} from "./generated/{name}/binder";\n\nconst output = parse{concept}(result.main_stuff);\n'
        )
        python = snippets[python_path]
        assert f"from pipelex_sdk.runs import RunResults\n\nfrom generated.{name}.models import {concept}\n" in python
        assert python.endswith(
            f'def read_output(result: RunResults) -> {concept}:\n    """The method returns one `{concept}`."""\n'
            f"    return {concept}.model_validate(result.main_stuff)\n"
        )
        assert "listItems" not in snippets[typescript_path]
        assert "TypeAdapter" not in python

    @pytest.mark.parametrize(("output", "multiplicity", "item_count"), [("Text[]", "variable", None), ("Text[3]", "fixed", 3)])
    def test_a_list_output_is_read_as_a_bare_list_or_in_its_envelope(
        self, make_cookbook: MakeCookbook, templates_dir: Path, output: str, multiplicity: str, item_count: int | None
    ):
        root = make_cookbook()
        package_dir = root / "methods" / "count_words"
        (package_dir / "bundle.mthds").write_text(WORDS_BUNDLE.replace('output = "Text"', f'output = "{output}"'), encoding="utf-8")
        contract = WORDS_CONTRACT.model_copy(
            update={"output": WORDS_CONTRACT.output.model_copy(update={"multiplicity": multiplicity, "item_count": item_count})}
        )
        (package_dir / "contract.json").write_text(contract.to_json(), encoding="utf-8")
        snippets = render_snippets(cookbook=load_cookbook(root), templates_dir=templates_dir)
        typescript_path, python_path = _snippet_files(root, "count_words")

        typescript = snippets[typescript_path]
        assert 'import { parseText } from "./generated/count_words/binder";\n' in typescript
        assert "if (Array.isArray(mainStuff)) {\n    return mainStuff;\n  }\n" in typescript
        assert '"items" in mainStuff && Array.isArray(mainStuff.items)' in typescript
        assert typescript.endswith("const output = listItems(result.main_stuff).map((item) => parseText(item));\n")
        python = snippets[python_path]
        assert "from pydantic import BaseModel, TypeAdapter\n\nfrom generated.count_words.models import Text\n" in python
        assert "class TextList(BaseModel):\n" in python
        assert "    items: list[Text]\n" in python
        assert "def read_output(result: RunResults) -> list[Text]:\n" in python
        assert "    output = TypeAdapter[list[Text] | TextList](list[Text] | TextList).validate_python(result.main_stuff)\n" in python
        assert python.endswith("    return output.items if isinstance(output, TextList) else output\n")

    def test_each_generated_tree_gets_a_sidecar_naming_the_packages_files(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        (root / "methods" / "extract_widgets" / "widgets.mthds").write_text('domain = "widgets"\n', encoding="utf-8")
        snippets = render_snippets(cookbook=load_cookbook(root), templates_dir=templates_dir)
        for relative_path, target in SIDECARS.items():
            sidecar = json.loads(snippets[root / "tests" / "snippets" / "extract_widgets" / relative_path.format(name="extract_widgets")])
            assert sidecar["generator"] == "pipelex-cookbook"
            assert sidecar["method"] == {"files": ["methods/extract_widgets/bundle.mthds", "methods/extract_widgets/widgets.mthds"]}
            assert sidecar["target"] == target
            assert "`make refresh` regenerates the tree from this file" in sidecar["comment"]

    def test_the_rendered_sidecars_read_cleanly_as_snippet_trees(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        for path, contents in render_all(cookbook=load_cookbook(root), templates_dir=templates_dir).items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf-8")
        (root / "tests" / "snippets" / "package.json").write_text("{}", encoding="utf-8")
        trees = find_trees(root)
        assert [(tree.directory.relative_to(root).as_posix(), tree.files, tree.target) for tree in trees] == [
            ("tests/snippets/count_words/python/generated/count_words", ["methods/count_words/bundle.mthds"], "python-pydantic"),
            ("tests/snippets/count_words/typescript/generated/count_words", ["methods/count_words/bundle.mthds"], "ts-zod"),
            ("tests/snippets/extract_widgets/python/generated/extract_widgets", ["methods/extract_widgets/bundle.mthds"], "python-pydantic"),
            ("tests/snippets/extract_widgets/typescript/generated/extract_widgets", ["methods/extract_widgets/bundle.mthds"], "ts-zod"),
        ]
        assert recipe_problems(root) == []

    def test_the_python_snippet_file_opens_with_its_inline_dependencies(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        snippets = render_snippets(cookbook=load_cookbook(root), templates_dir=templates_dir)
        snippet = snippets[root / "tests" / "snippets" / "count_words" / "python" / "snippet.py"]
        assert snippet.startswith('# /// script\n# requires-python = ">=3.11"\n# dependencies = ["pipelex-sdk==')
        assert "\n# ///\n# Generated by `make render` from methods/count_words/ and cookbook.toml" in snippet

    def test_render_all_writes_the_pages_their_snippet_files_and_the_front_page(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        rendered = render_all(cookbook=load_cookbook(root), templates_dir=templates_dir)
        assert sorted(path.relative_to(root).as_posix() for path in rendered) == [
            "README.md",
            "methods/count_words/README.md",
            "methods/extract_widgets/README.md",
            "tests/snippets/count_words/python/generated/count_words/sources.json",
            "tests/snippets/count_words/python/snippet.py",
            "tests/snippets/count_words/typescript/generated/count_words/sources.json",
            "tests/snippets/count_words/typescript/snippet.ts",
            "tests/snippets/extract_widgets/python/generated/extract_widgets/sources.json",
            "tests/snippets/extract_widgets/python/snippet.py",
            "tests/snippets/extract_widgets/typescript/generated/extract_widgets/sources.json",
            "tests/snippets/extract_widgets/typescript/snippet.ts",
        ]

    @pytest.mark.parametrize("extra_characters", [0, 1])
    def test_a_sample_above_the_limit_is_fetched_by_every_snippet(self, make_cookbook: MakeCookbook, templates_dir: Path, extra_characters: int):
        root = make_cookbook()
        # `{"text": "…"}` serialises to the text's length and twelve characters more.
        text = "x" * (INLINE_INPUTS_LIMIT - 12 + extra_characters)
        (root / "methods" / "count_words" / "inputs.json").write_text(json.dumps({"text": text}), encoding="utf-8")
        cookbook = load_cookbook(root)
        page = render_pages(cookbook=cookbook, templates_dir=templates_dir)[root / "methods" / "count_words" / "README.md"]
        snippets = render_snippets(cookbook=cookbook, templates_dir=templates_dir)
        typescript = snippets[root / "tests" / "snippets" / "count_words" / "typescript" / "snippet.ts"]
        python = snippets[root / "tests" / "snippets" / "count_words" / "python" / "snippet.py"]
        inputs_url = "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.9.0/methods/count_words/inputs.json"
        fetches = [
            f"each snippet below fetches them from the method's [`inputs.json`]({inputs_url})",
            f'const response = await fetch("{inputs_url}");\nconst inputs = (await response.json()) as Record<string, unknown>;',
            "  inputs,\n",
            f'    inputs = httpx.get("{inputs_url}").json()',
            "            inputs=inputs,\n",
            f"START=$(curl -sL {inputs_url} |\n  jq -c '{{method_ref: \"github.com/Pipelex/pipelex-cookbook/count_words@v0.9.0\", inputs: .}}' |",
        ]
        if extra_characters:
            # Only "The sample" still quotes it.
            assert page.count(text) == 1
            assert all(fetch in page for fetch in fetches)
            _split_snippet(typescript, block=_fenced_block(page, language="ts"))
            _split_snippet(python, block=_fenced_block(page, language="python"))
            assert '# dependencies = ["pipelex-sdk==0.12.0", "httpx>=0.25", "pydantic>=2.10.6"]\n' in python
        else:
            # "The sample" quotes it, and the TypeScript, Python and HTTP snippets write it out.
            assert page.count(text) == 4
            assert not any(fetch in page for fetch in fetches)
            assert "import httpx" not in python
            assert '# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]\n' in python

    @pytest.mark.parametrize(
        ("inputs", "unchecked"),
        [
            ({"catalogue": {"url": WIDGETS_SAMPLE_URL}}, False),
            ({"catalogue": ["a", "b"], "note": "text"}, False),
            ({"catalogue": [{"url": WIDGETS_SAMPLE_URL}, {"url": WIDGETS_SAMPLE_URL}]}, True),
            ({"catalogue": {"url": WIDGETS_SAMPLE_URL}, "pages": 3}, True),
            ({"catalogue": [{"url": WIDGETS_SAMPLE_URL}], "padding": "x" * INLINE_INPUTS_LIMIT}, False),
        ],
    )
    def test_a_python_sample_the_sdk_type_refuses_leaves_argument_types_unchecked_in_the_file_only(
        self, make_cookbook: MakeCookbook, templates_dir: Path, inputs: dict[str, JsonValue], unchecked: bool
    ):
        root = make_cookbook()
        (root / "methods" / "extract_widgets" / "inputs.json").write_text(json.dumps(inputs), encoding="utf-8")
        cookbook = load_cookbook(root)
        page = render_pages(cookbook=cookbook, templates_dir=templates_dir)[root / "methods" / "extract_widgets" / "README.md"]
        python = render_snippets(cookbook=cookbook, templates_dir=templates_dir)[
            root / "tests" / "snippets" / "extract_widgets" / "python" / "snippet.py"
        ]
        header, _ = _split_snippet(python, block=_fenced_block(page, language="python"))
        assert ("\n# pyright: reportArgumentType=false\n" in header) is unchecked
        assert "pyright" not in page

    def test_python_strings_are_quoted_as_ruff_quotes_them(self):
        assert python_literal("plain") == '"plain"'
        assert python_literal('say "hi"') == "'say \"hi\"'"
        assert python_literal("it's") == '"it\'s"'

    def test_snippet_literals_follow_each_language(self):
        value: JsonValue = {"document": {"url": "https://example.com/a.pdf", "pages": [1, 2], "ocr": True, "note": None}, "two words": "x"}
        assert typescript_literal(value) == (
            "{\n"
            "  document: {\n"
            '    url: "https://example.com/a.pdf",\n'
            "    pages: [\n      1,\n      2,\n    ],\n"
            "    ocr: true,\n"
            "    note: null,\n"
            "  },\n"
            '  "two words": "x",\n'
            "}"
        )
        assert python_literal(value) == (
            "{\n"
            '    "document": {\n'
            '        "url": "https://example.com/a.pdf",\n'
            '        "pages": [\n            1,\n            2,\n        ],\n'
            '        "ocr": True,\n'
            '        "note": None,\n'
            "    },\n"
            '    "two words": "x",\n'
            "}"
        )

    @pytest.mark.parametrize(
        ("type_expression", "expected"),
        [
            ("text", "text"),
            ("date", "a date"),
            ("integer", "an integer"),
            ("list[text]", "a list of texts"),
            ("list[GanttTaskDetails]", "a list of `GanttTaskDetails`"),
            ("Invoice", "an `Invoice`"),
            ("Milestone", "a `Milestone`"),
            ("text or integer", "text or an integer"),
            ("list[text or integer]", "a list of texts or integers"),
            ("list[text] or list[Invoice]", "a list of texts or a list of `Invoice`"),
        ],
    )
    def test_type_phrases(self, type_expression: str, expected: str):
        assert type_phrase(type_expression) == expected
