import re
from pathlib import Path

import pytest
from pydantic import JsonValue

from scripts.cookbook import load_cookbook
from scripts.exceptions import CookbookLayoutError
from scripts.render import python_literal, render_all, render_front_page, render_pages, render_snippets, type_phrase, typescript_literal
from tests.tooling.test_data import WIDGETS_SAMPLE_URL, MakeCookbook

# Each snippet file, by its path under `tests/snippets/<name>/`, with the fence its block has on the page and the prefix of its comment lines.
SNIPPET_FILES = {"typescript/snippet.ts": ("ts", "//"), "python/snippet.py": ("python", "#")}


def _fenced_block(page: str, *, language: str) -> str:
    """The body of the page's one code block fenced as `language`, up to and including its last newline."""
    blocks: list[str] = re.findall(rf"^```{language}\n(.*?)^```$", page, flags=re.MULTILINE | re.DOTALL)
    [block] = blocks
    return block


class TestRender:
    def test_page_is_rendered_from_the_package_and_its_editorial_entry(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        pages = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)
        page = pages[root / "methods" / "extract_widgets" / "README.md"]

        address = "github.com/Pipelex/pipelex-cookbook/extract_widgets@v0.9.0"
        assert page.startswith("<!-- Generated by `make render` from methods/extract_widgets/")
        assert "# Widget extraction\n\nRead a catalogue page and list every widget on it.\n" in page
        assert f"`{address}` · [bundle.mthds](bundle.mthds) · [sample catalogue]({WIDGETS_SAMPLE_URL})" in page
        assert "**Takes** `catalogue`, an image (`CataloguePage`): A page of a widget catalogue." in page
        assert "**Returns** a `WidgetList`: Every widget on the page." in page
        assert "- `widgets`, a list of `Widget`: The widgets, in page order." in page
        assert f"> Run {address} on {WIDGETS_SAMPLE_URL}" in page
        assert "In ChatGPT you can attach your own file instead of the link" in page
        assert f'  method_ref: "{address}",' in page
        assert f"npm create @pipelex/method-app@latest widgets-app -- --method {address}" in page
        assert f"Copy {address} into ./widgets, add each widget's price to what it extracts, prove it" in page
        # The Must lines are "What you get", a continuation line folded into its labelled line.
        assert "- `widgets` holds three widgets: Sprocket, Flange and Gasket.\n" in page
        assert "- Each widget's `colour` is the colour printed beside it, in any wording.\n" in page
        assert "A widget listed twice" not in page

    def test_page_without_an_editorial_entry_comes_from_the_manifest(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        pages = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)
        page = pages[root / "methods" / "count_words" / "README.md"]

        address = "github.com/Pipelex/pipelex-cookbook/count_words@v0.9.0"
        inputs_url = "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.9.0/methods/count_words/inputs.json"
        assert "# Word Count\n\nCount the words of a text.\n" in page
        assert f"`{address}` · [bundle.mthds](bundle.mthds)\n" in page
        assert "**Takes** `text`, a text (`Text`)." in page
        # A native concept's description only restates its type, so the Returns line stops at the concept.
        assert "**Returns** a `Text`.\n" in page
        assert f"> Run {address} with the sample inputs in {inputs_url}" in page
        assert "attach your own file" not in page
        assert f"npm create @pipelex/method-app@latest count-words-app -- --method {address}" in page
        assert f"Copy {address} into ./count_words, adapt what it does to my case, prove it" in page
        assert f"curl -sLo inputs.json {inputs_url}" in page
        assert 'inputs={\n                "text": "The quick brown fox",\n            },' in page

    def test_the_front_page_lists_every_method_and_keeps_its_own_lines(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        front_page = render_front_page(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "README.md"]

        assert front_page.startswith("# Fixture cookbook\n\nWritten by hand.\n\n<!-- BEGIN methods")
        assert front_page.endswith("<!-- END methods -->\n\n## Also written by hand\n")
        assert "- **[Word Count](methods/count_words/)**: Count the words of a text.\n" in front_page
        assert "- **[Widget extraction](methods/extract_widgets/)**: Read a catalogue page and list every widget on it.\n" in front_page
        assert "[Pipelex method library](https://github.com/Pipelex/methods)" in front_page

    def test_a_second_render_of_the_front_page_changes_nothing(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        cookbook = load_cookbook(root)
        for path, contents in render_all(cookbook=cookbook, templates_dir=templates_dir).items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf-8")
        assert render_front_page(cookbook=cookbook, templates_dir=templates_dir)[root / "README.md"] == (root / "README.md").read_text(
            encoding="utf-8"
        )

    def test_a_front_page_without_its_region_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        (root / "README.md").write_text("# Fixture cookbook\n", encoding="utf-8")
        with pytest.raises(CookbookLayoutError, match="must hold one region for the list of methods"):
            render_all(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_the_tag_is_v_and_the_version_file(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook(version="1.2.3")
        pages = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)
        for page in pages.values():
            assert "@v1.2.3" in page
            assert "@v0.9.0" not in page

    def test_a_must_line_citing_a_planted_fact_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        key_path = root / "methods" / "extract_widgets" / "key.md"
        key_path.write_text(key_path.read_text(encoding="utf-8").replace("Sprocket, Flange and Gasket.\nM2", "those of F1.\nM2"), encoding="utf-8")
        with pytest.raises(CookbookLayoutError, match="M1 cites a planted fact"):
            render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_a_package_without_a_contract_snapshot_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        (root / "methods" / "count_words" / "contract.json").unlink()
        with pytest.raises(CookbookLayoutError, match="run `make refresh`"):
            render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_a_chatbot_sentence_that_does_not_format_is_refused(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        settings_path = root / "cookbook.toml"
        settings_path.write_text(
            settings_path.read_text(encoding="utf-8").replace(
                'app_dir = "widgets-app"', 'chatbot = "Run {address} on {samples"\napp_dir = "widgets-app"'
            ),
            encoding="utf-8",
        )
        with pytest.raises(CookbookLayoutError, match="does not format"):
            render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)

    def test_only_an_exact_concept_wrapper_is_unwrapped_in_the_snippets(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        inputs_path = root / "methods" / "count_words" / "inputs.json"
        inputs_path.write_text('{"text": {"title": "Fox", "content": "The quick brown fox"}}', encoding="utf-8")
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "count_words" / "README.md"]
        assert '"title": "Fox"' in page

    def test_an_input_holding_a_list_of_files_links_each_one(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        first, second = "https://example.com/a.png", "https://example.com/b.png"
        inputs_path = root / "methods" / "extract_widgets" / "inputs.json"
        inputs_path.write_text(f'{{"catalogue": [{{"url": "{first}"}}, {{"url": "{second}"}}]}}', encoding="utf-8")
        page = render_pages(cookbook=load_cookbook(root), templates_dir=templates_dir)[root / "methods" / "extract_widgets" / "README.md"]
        assert f"[sample catalogue 1]({first}) · [sample catalogue 2]({second})" in page
        assert f"on {first} and {second}" in page

    def test_each_snippet_file_is_the_pages_snippet_under_comment_lines(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        cookbook = load_cookbook(root)
        pages = render_pages(cookbook=cookbook, templates_dir=templates_dir)
        snippets = render_snippets(cookbook=cookbook, templates_dir=templates_dir)
        assert sorted(snippets) == sorted(
            root / "tests" / "snippets" / name / relative_path for name in ("count_words", "extract_widgets") for relative_path in SNIPPET_FILES
        )
        for name in ("count_words", "extract_widgets"):
            page = pages[root / "methods" / name / "README.md"]
            for relative_path, (language, comment) in SNIPPET_FILES.items():
                snippet = snippets[root / "tests" / "snippets" / name / relative_path]
                block = _fenced_block(page, language=language)
                assert f"github.com/Pipelex/pipelex-cookbook/{name}@v0.9.0" in block
                assert snippet.endswith(block)
                header = snippet.removesuffix(block)
                assert header.endswith("never edit this file by hand.\n")
                assert all(line.startswith(comment) for line in header.splitlines())

    def test_the_python_snippet_file_opens_with_its_inline_dependencies(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        snippets = render_snippets(cookbook=load_cookbook(root), templates_dir=templates_dir)
        snippet = snippets[root / "tests" / "snippets" / "count_words" / "python" / "snippet.py"]
        assert snippet.startswith('# /// script\n# requires-python = ">=3.11"\n# dependencies = ["pipelex-sdk==')
        assert "\n# ///\n# Generated by `make render` from methods/count_words/ and cookbook.toml" in snippet

    def test_render_all_writes_the_pages_their_snippet_files_and_the_front_page(self, make_cookbook: MakeCookbook, templates_dir: Path):
        root = make_cookbook()
        rendered = render_all(cookbook=load_cookbook(root), templates_dir=templates_dir)
        assert sorted(path.relative_to(root).as_posix() for path in rendered) == [
            "README.md",
            "methods/count_words/README.md",
            "methods/extract_widgets/README.md",
            "tests/snippets/count_words/python/snippet.py",
            "tests/snippets/count_words/typescript/snippet.ts",
            "tests/snippets/extract_widgets/python/snippet.py",
            "tests/snippets/extract_widgets/typescript/snippet.ts",
        ]

    def test_python_strings_are_quoted_as_ruff_quotes_them(self):
        assert python_literal("plain") == '"plain"'
        assert python_literal('say "hi"') == "'say \"hi\"'"
        assert python_literal("it's") == '"it\'s"'

    def test_snippet_literals_follow_each_language(self):
        value: JsonValue = {"document": {"url": "https://example.com/a.pdf", "pages": [1, 2], "ocr": True, "note": None}, "two words": "x"}
        assert typescript_literal(value) == (
            "{\n"
            "  document: {\n"
            '    url: "https://example.com/a.pdf",\n'
            "    pages: [\n      1,\n      2,\n    ],\n"
            "    ocr: true,\n"
            "    note: null,\n"
            "  },\n"
            '  "two words": "x",\n'
            "}"
        )
        assert python_literal(value) == (
            "{\n"
            '    "document": {\n'
            '        "url": "https://example.com/a.pdf",\n'
            '        "pages": [\n            1,\n            2,\n        ],\n'
            '        "ocr": True,\n'
            '        "note": None,\n'
            "    },\n"
            '    "two words": "x",\n'
            "}"
        )

    @pytest.mark.parametrize(
        ("type_expression", "expected"),
        [
            ("text", "text"),
            ("date", "a date"),
            ("integer", "an integer"),
            ("list[text]", "a list of texts"),
            ("list[GanttTaskDetails]", "a list of `GanttTaskDetails`"),
            ("Invoice", "an `Invoice`"),
            ("Milestone", "a `Milestone`"),
        ],
    )
    def test_type_phrases(self, type_expression: str, expected: str):
        assert type_phrase(type_expression) == expected
