// Generated by `make render` from methods/discord_newsletter/ and cookbook.toml, as the TypeScript snippet of methods/discord_newsletter/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/discord_newsletter@v0.18.0",
  inputs: {
    discord_channel_updates: [
      {
        name: "Introduce-Yourself",
        position: 4,
        messages: [
          {
            author: "Maria Chen (CyberSynth)",
            content: "## [**Maria Chen**](https://www.linkedin.com/in/fakeprofile1) \n\n*Founder & Lead AI Architect @ [CyberSynth](https://cybersynth.dev) · We build secure, decentralized AI systems.*\n\nHi everyone! I've been in the cybersecurity space for over a decade, transitioning into AI security about 3 years ago. I'm a big believer in open-source and building tools that empower developers. In my other life, I'm a competitive rock climber.\n\nSpecial power: Can debug race conditions in my sleep.\n\n📍 San Francisco, CA (PST)",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "David Lee (DataWeave)",
            content: "## [**David Lee**](https://www.linkedin.com/in/fakeprofile2)\n*Head of Data @ [DataWeave](https://dataweave.io) · Making data pipelines intelligent and autonomous.*\n\nHello! I'm David. I've been wrestling with large-scale data systems for my entire career, from Hadoop clusters to modern data lakes. Now I'm focused on applying LLMs to data engineering workflows. I also contribute to Apache Arrow.\n\nSpecial power: I roast my own coffee beans. The perfect pour-over is my art form.\n\n📍 London, UK (GMT)",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Sofia Rodriguez (LogicLoom)",
            content: "## [Sofia Rodriguez](https://www.linkedin.com/in/fakeprofile3)\n\n*Co-founder & CEO @ [LogicLoom](https://logicoom.ai) · LogicLoom is a platform for building and verifying complex agentic workflows. Think of it as unit testing for AI agents.*\n\nHey all! I'm a former philosophy professor turned tech entrepreneur. My passion is at the intersection of formal logic and machine learning. LogicLoom is my attempt to bring more rigor and reliability to the AI space.\n\nSpecial power: I can recite the first 200 digits of pi. It's a completely useless but fun party trick.\n\n📍 Berlin, DE (CET)",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Alex Ivanov (CogniCore)",
            content: "## [**Alex Ivanov**](https://www.linkedin.com/in/fakeprofile4/)\n*Senior ML Engineer @ [CogniCore](https://cognicore.tech) · We're creating next-gen multimodal models for creative industries.*\n\nHey everyone, I'm Alex. I have a background in computer graphics and generative art. At CogniCore, I work on models that can understand and generate video, audio, and text seamlessly. I'm always down to talk about diffusion models or creative AI.\n\nSpecial power: I built a robot that paints abstract art.\n\n📍 Tokyo, JP (JST)",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Chloe Dubois (Aether AI)",
            content: "## [**Chloe Dubois**](https://www.linkedin.com/in/fakeprofile5/)\n*CTO @ [Aether AI](https://aetherai.com) · Building efficient AI for edge devices.*\n\nHi! I'm Chloe. My focus is on model optimization, quantization, and running complex neural networks on resource-constrained hardware. Before Aether, I was at a major chip designer working on their mobile AI accelerators. When I'm not coding, I'm usually hiking in the mountains.\n\n📍 Grenoble, FR (CET)",
            attachments: [],
            embeds: [],
            link: "",
          },
        ],
      },
      {
        name: "Troll",
        position: 55,
        messages: [
          {
            author: "Ben Carter (Momentum ML)",
            content: "The original 'cloud'.\n\nIn reply to Ben Carter (Momentum ML)'s message:\nThey called it 'The Mainframe'. We've come full circle.",
            attachments: [],
            embeds: [
              {
                title: "History of the Mainframe Computer",
                description: "A look back at the powerful machines that started the computing revolution and how their concepts are still relevant today.",
                type: "article",
              },
            ],
            link: "",
          },
          {
            author: "Ben Carter (Momentum ML)",
            content: "They called it 'The Mainframe'. We've come full circle.",
            attachments: [
              {
                name: "ancient_computer.jpg",
              },
            ],
            embeds: [],
            link: "",
          },
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "My LLM when I ask it to write a single line of CSS.",
            attachments: [],
            embeds: [
              {
                title: "When AI Overthinks The Problem",
                description: "A comedic sketch about an AI assistant that writes a 10-page thesis on the philosophical implications of a button color choice.",
                type: "video",
              },
            ],
            link: "",
          },
          {
            author: "Isabella Rossi (FluidStack)",
            content: "I used QuantumLeap to optimize my fantasy football picks. Thanks for the server credits!",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Liam O'Malley (CoreLogic)",
            content: "Haha, exactly! We just thought it sounded cool. And it's an anagram for 'Cool Gil'.",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "You know Liam O'Malley (CoreLogic) is in here, right? They're gonna have questions.",
            attachments: [
              {
                name: "corelogic_logo_meme.png",
              },
            ],
            embeds: [],
            link: "",
          },
          {
            author: "Ben Carter (Momentum ML)",
            content: "This company name is a bold choice.",
            attachments: [
              {
                name: "screenshot_startup_name.png",
              },
            ],
            embeds: [],
            link: "",
          },
        ],
      },
      {
        name: "🧠-Knowledge",
        position: 7,
        messages: [
          {
            author: "Fatima Al-Jamil (Synthax)",
            content: "Really insightful talk on data synthesis.",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Fatima Al-Jamil (Synthax)",
            content: "For anyone interested in the future of synthetic data for training, this talk from the 'AI Engineering' summit was fantastic.",
            attachments: [],
            embeds: [
              {
                title: "Synthetic Data: The Key to Unlocking AGI? - AI Engineering Summit 2024",
                description: "Dr. Eva Rostova explores cutting-edge techniques for generating high-quality synthetic data and its impact on model performance and safety.",
                type: "video",
              },
            ],
            link: "",
          },
        ],
      },
      {
        name: "🎉-Achievements",
        position: 10,
        messages: [
          {
            author: "Chloe Dubois (Aether AI)",
            content: "We just open-sourced our model quantization toolkit! Would love to get feedback from the community.",
            attachments: [],
            embeds: [
              {
                title: "Announcing AetherLite: Our Open-Source Quantization Library",
                description: "Developers can now use AetherLite to shrink and accelerate their models for deployment on edge devices with minimal performance loss.",
                type: "article",
              },
            ],
            link: "",
          },
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "Our work on generative graph networks was featured by Google AI's research blog!",
            attachments: [],
            embeds: [
              {
                title: "NeuroNet's Groundbreaking Research in Graph-based RAG",
                description: "Highlighting a new approach that combines Knowledge Graphs with LLMs for more accurate and explainable responses. A collaborative effort with leading academics...",
                type: "article",
              },
            ],
            link: "",
          },
          {
            author: "Ethan Brown (CodeFlow)",
            content: "We've finally released v1.0 of the Plakar backup format! A modern, content-addressable format for data snapshots. No more tarballs!",
            attachments: [],
            embeds: [
              {
                title: "Plakar v1.0: A New Era for Data Backups",
                description: "Moving beyond legacy formats, Plakar offers speed, deduplication, and encryption for modern data protection needs.",
                type: "article",
              },
            ],
            link: "",
          },
          {
            author: "Ben Carter (Momentum ML)",
            content: "Nope, I started by building custom ETL pipelines for scientific research data. Much more chaotic than any CRM! 😂\n\nIn reply to Kenji Tanaka (NeuroNet)'s message:\nI thought you started out as a data warehouse consultant?",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "I thought you started out as a data warehouse consultant?",
            attachments: [],
            embeds: [],
            link: "",
          },
        ],
      },
      {
        name: "🛡-Cyber",
        position: 17,
        messages: [
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "Wow, I missed this one. That's a nasty bug.",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "Another critical sudo vulnerability just dropped.",
            attachments: [],
            embeds: [
              {
                title: "New Sudo Vulnerability Allows Any Local User to Gain Root Privileges",
                description: "Two new vulnerabilities have been discovered in the ubiquitous Sudo command-line utility, allowing local attackers to escalate their privileges to root on most Linux and macOS systems.",
                type: "article",
              },
            ],
            link: "",
          },
          {
            author: "Ben Carter (Momentum ML)",
            content: "This is a baffling decision. They're deprecating their native desktop apps to focus on a web extension that barely works half the time and violates browser extension best practices. A huge step backwards.\n\nIn reply to Ben Carter (Momentum ML)'s message:\nIf you use Keeper for password management, you might want to consider migrating in the next couple of months. For teams, self-hosted VaultWarden or 1Password are far superior anyway.",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Ben Carter (Momentum ML)",
            content: "If you use Keeper for password management, you might want to consider migrating in the next couple of months. For teams, self-hosted VaultWarden or 1Password are far superior anyway.",
            attachments: [
              {
                name: "keeper_deprecation_email.png",
              },
            ],
            embeds: [],
            link: "",
          },
        ],
      },
      {
        name: "🇺🇸-San-Francisco",
        position: 30,
        messages: [
          {
            author: "Maria Chen (CyberSynth)",
            content: "We're hosting a casual rooftop get-together tomorrow in SF for folks in the AI space. If you're around and want to talk shop over some drinks and snacks, come by! Lucas Müller (ConnectSphere) will be there too!",
            attachments: [],
            embeds: [
              {
                title: "The AI Founders Mixer · Luma",
                description: "A casual networking event for AI founders, researchers, and builders. Join us on the rooftop for good conversation and great views.",
                type: "article",
              },
            ],
            link: "",
          },
        ],
      },
      {
        name: "🇩🇪-Berlin",
        position: 51,
        messages: [
          {
            author: "Leo Schmidt (Bio-Nexus)",
            content: "Perfect, thank you so much!\n\nIn reply to Sofia Rodriguez (LogicLoom)'s message:\nLeo Schmidt (Bio-Nexus) you can book a free trial day pass here: [link to fake booking site]. For a monthly desk, you'll have to contact them directly, but they're usually pretty flexible.",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Sofia Rodriguez (LogicLoom)",
            content: "Leo Schmidt (Bio-Nexus) you can book a free trial day pass here: [link to fake booking site]. For a monthly desk, you'll have to contact them directly, but they're usually pretty flexible.",
            attachments: [],
            embeds: [
              {
                title: "Factory Berlin | Memberships",
                description: "Join our community of creators. We offer flexible memberships for individuals and teams, with access to our vibrant workspaces and events.",
                type: "article",
              },
            ],
            link: "",
          },
          {
            author: "Kenji Tanaka (NeuroNet)",
            content: "Maybe Sofia Rodriguez (LogicLoom) knows a good spot!",
            attachments: [],
            embeds: [],
            link: "",
          },
          {
            author: "Leo Schmidt (Bio-Nexus)",
            content: "@here Hey Berliners! Any recommendations for a good, affordable co-working space? I'm a newly-bootstrapped founder, so my budget is tight. Thanks!",
            attachments: [],
            embeds: [],
            link: "",
          },
        ],
      },
    ],
  },
});
console.log(result.main_stuff);
