// Generated by `make render` from methods/discord_newsletter/ and cookbook.toml, as the TypeScript snippet of methods/discord_newsletter/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const response = await fetch("https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/v0.18.0/methods/discord_newsletter/inputs.json");
const inputs = (await response.json()) as Record<string, unknown>;
const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/discord_newsletter@v0.18.0",
  inputs,
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/discord_newsletter/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
// pipe's declared output, so tsc fails when the page names a concept those types no longer hold.
import { parseHtmlNewsletter } from "./generated/discord_newsletter/binder";

const output = parseHtmlNewsletter(result.main_stuff);
