// Generated by `make render` from methods/gen_synthetic_data/ and cookbook.toml, as the TypeScript snippet of methods/gen_synthetic_data/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/gen_synthetic_data@v0.19.1",
  inputs: {
    data_description: {
      text: "# Student Profile: [Student Name]\n\n## Basic Info\n- **Current Performance**: [Struggling / Average / Advanced]\n\n## Learning Style\n- **Learns Best With**: [Visual examples / Step-by-step text / Hands-on practice / Videos]\n- **Pace**: [Needs more time / Normal / Fast learner]\n- **Complexity**: [Prefers simple explanations / Balanced / Likes deep details]\n\n## Background\n- **Strengths**: [subjects or topics they're good at]\n- **Needs Help With**: [areas where they struggle]\n- **Prior Knowledge**: [relevant topics they already know]\n\n## Interests\n- **Hobbies/Interests**: [e.g., soccer, video games, music]\n- **Career Goals**: [if any - e.g., engineer, doctor, undecided]\n\n## Preferences\n- **Example Style**: [Many real-world examples / Abstract concepts / Mix]\n- **Question Format**: [Multiple choice / Short answer / Open discussion]\n",
    },
    nb_samples: {
      number: 5,
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/gen_synthetic_data/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
// pipe's declared output, so tsc fails when the page names a concept those types no longer hold.
import { parseSample } from "./generated/gen_synthetic_data/binder";

/** The items of a list output: the SDK documents the envelope {"items": [...]}, while the hosted API answers a bare list today. */
function listItems(mainStuff: unknown): unknown[] {
  if (Array.isArray(mainStuff)) {
    return mainStuff;
  }
  if (typeof mainStuff === "object" && mainStuff !== null && "items" in mainStuff && Array.isArray(mainStuff.items)) {
    return mainStuff.items;
  }
  throw new Error('expected a list output, bare or as {"items": [...]}');
}

const output = listItems(result.main_stuff).map((item) => parseSample(item));
