# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0"]
# ///
# Generated by `make render` from methods/blog_article_generator/ and cookbook.toml, as the Python snippet of methods/blog_article_generator/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/blog_article_generator@v0.18.0",
            inputs={
                "user_prompt": {
                    "text": "Write a fun and engaging blog article",
                    "topic": "Capybara",
                    "audience": "Kids",
                    "tone": "Casual",
                    "length": "Long",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())
