# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0"]
# ///
# Generated by `make render` from methods/gen_synthetic_data/ and cookbook.toml, as the Python snippet of methods/gen_synthetic_data/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/gen_synthetic_data@v0.18.0",
            inputs={
                "data_description": {
                    "text": "# Student Profile: [Student Name]\n\n## Basic Info\n- **Current Performance**: [Struggling / Average / Advanced]\n\n## Learning Style\n- **Learns Best With**: [Visual examples / Step-by-step text / Hands-on practice / Videos]\n- **Pace**: [Needs more time / Normal / Fast learner]\n- **Complexity**: [Prefers simple explanations / Balanced / Likes deep details]\n\n## Background\n- **Strengths**: [subjects or topics they're good at]\n- **Needs Help With**: [areas where they struggle]\n- **Prior Knowledge**: [relevant topics they already know]\n\n## Interests\n- **Hobbies/Interests**: [e.g., soccer, video games, music]\n- **Career Goals**: [if any - e.g., engineer, doctor, undecided]\n\n## Preferences\n- **Example Style**: [Many real-world examples / Abstract concepts / Mix]\n- **Question Format**: [Multiple choice / Short answer / Open discussion]\n",
                },
                "nb_samples": {
                    "number": 5,
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())
