# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/gen_synthetic_data/ and cookbook.toml, as the Python snippet of methods/gen_synthetic_data/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/gen_synthetic_data@v0.18.0",
            inputs={
                "data_description": {
                    "text": "# Student Profile: [Student Name]\n\n## Basic Info\n- **Current Performance**: [Struggling / Average / Advanced]\n\n## Learning Style\n- **Learns Best With**: [Visual examples / Step-by-step text / Hands-on practice / Videos]\n- **Pace**: [Needs more time / Normal / Fast learner]\n- **Complexity**: [Prefers simple explanations / Balanced / Likes deep details]\n\n## Background\n- **Strengths**: [subjects or topics they're good at]\n- **Needs Help With**: [areas where they struggle]\n- **Prior Knowledge**: [relevant topics they already know]\n\n## Interests\n- **Hobbies/Interests**: [e.g., soccer, video games, music]\n- **Career Goals**: [if any - e.g., engineer, doctor, undecided]\n\n## Preferences\n- **Example Style**: [Many real-world examples / Abstract concepts / Mix]\n- **Question Format**: [Multiple choice / Short answer / Open discussion]\n",
                },
                "nb_samples": {
                    "number": 5,
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/gen_synthetic_data/, so that the type checker holds the page's call to the concept its "Returns" line names.
from pipelex_sdk.runs import RunResults
from pydantic import BaseModel, TypeAdapter

from generated.gen_synthetic_data.models import Sample


class SampleList(BaseModel):
    """The envelope `{"items": [...]}` the SDK documents for a list output."""

    items: list[Sample]


def read_output(result: RunResults) -> list[Sample]:
    """The method returns a list of `Sample`, which the SDK documents as the envelope and the hosted API answers as a bare list today."""
    output = TypeAdapter[list[Sample] | SampleList](list[Sample] | SampleList).validate_python(result.main_stuff)
    return output.items if isinstance(output, SampleList) else output
