# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/extract_generic/ and cookbook.toml, as the Python snippet of methods/extract_generic/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/extract_generic@v0.18.0",
            inputs={
                "document": {
                    "url": "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_generic/fintech_article_with_text_in_images.pdf",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/extract_generic/, so that the type checker holds the page's call to the concept its "Returns" line names.
from pipelex_sdk.runs import RunResults
from pydantic import BaseModel, TypeAdapter

from generated.extract_generic.models import Text


class TextList(BaseModel):
    """The envelope `{"items": [...]}` the SDK documents for a list output."""

    items: list[Text]


def read_output(result: RunResults) -> list[Text]:
    """The method returns a list of `Text`, which the SDK documents as the envelope and the hosted API answers as a bare list today."""
    output = TypeAdapter[list[Text] | TextList](list[Text] | TextList).validate_python(result.main_stuff)
    return output.items if isinstance(output, TextList) else output
