# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0"]
# ///
# Generated by `make render` from methods/extract_generic/ and cookbook.toml, as the Python snippet of methods/extract_generic/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/extract_generic@v0.18.0",
            inputs={
                "document": {
                    "url": "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_generic/fintech_article_with_text_in_images.pdf",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())
