# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/research_report/ and cookbook.toml, as the Python snippet of methods/research_report/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/research_report@v0.19.1",
            inputs={
                "question": {
                    "text": "What are the most promising approaches to improving battery energy density for electric vehicles?",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/research_report/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
# pipe's declared output, so the type checker fails when the page names a concept those types no longer hold.
from pipelex_sdk.runs import RunResults

from generated.research_report.models import FormattedReport


def read_output(result: RunResults) -> FormattedReport:
    """The method returns one `FormattedReport`."""
    return FormattedReport.model_validate(result.main_stuff)
