# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0"]
# ///
# Generated by `make render` from methods/research_report/ and cookbook.toml, as the Python snippet of methods/research_report/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/research_report@v0.18.0",
            inputs={
                "question": {
                    "text": "What are the most promising approaches to improving battery energy density for electric vehicles?",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())
