"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class DocumentPassage(StructuredContent):
    """A verbatim passage extracted from a source document, with full citation metadata, used as grounded evidence for downstream synthesis."""

    document_identifier: str = Field(
        ...,
        description=(
            "The filename, title, or URL identifying which document the passage is from. Use whatever identifying information is "
            "available in the page content."
        ),
    )
    page_number: Optional[int] = Field(
        default=None, description="The page number within the source document. Use 1 if the document has no clear pagination."
    )
    quote: str = Field(
        ...,
        description=(
            "The exact text from the source, copied verbatim. No paraphrasing, no ellipsis beyond what is in the source, no "
            "reformatting beyond preserving the original words."
        ),
    )
    relevance_reasoning: str = Field(
        ..., description="Brief explanation of how this passage relates to the question or one of its sub-questions. One or two sentences."
    )
    sub_question_addressed: Optional[str] = Field(
        default=None, description="Which sub-question from the question analysis this passage helps address. Use the full text of the sub-question."
    )
