"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class document_qa__ReferenceCount(StructuredContent):
    """
    Specific output structure for this example's question — how many references in the report come from the report's own
    research center. Demonstrates how to output a typed structure tailored to the question rather than a free-form text
    answer.
    """

    count: int = Field(..., description="The number of references coming from the report's own research center.")
    explanation: str = Field(..., description="Short prose justification grounded in the cited passages.")
