"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Any, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class document_qa__EvidenceAssessment(StructuredContent):
    """
    A critical assessment of the retrieved evidence — whether it is sufficient to answer the question, which sub-questions
    have coverage, and whether any contradictions were detected across sources.
    """

    sufficiency: Literal["sufficient", "partial", "insufficient", "none"] = Field(
        ..., description="Overall sufficiency of the evidence relative to the question"
    )
    covered_sub_questions: List[Any] = Field(..., description="Sub-questions for which at least one retrieved passage provides evidence.")
    uncovered_sub_questions: List[Any] = Field(
        ..., description="Sub-questions for which no retrieved passage provides evidence. Empty list if coverage is complete."
    )
    contradictions: Optional[List[Any]] = Field(
        default=None,
        description=(
            "Specific contradictions detected across the retrieved passages — where two or more passages make incompatible claims "
            "about the same fact. Each item describes the conflict and cites the conflicting passages."
        ),
    )
    notes: Optional[str] = Field(default=None, description="Any other observations about the evidence: gaps, weak inferences, or quality concerns.")
