"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Any, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class QuestionAnalysis(StructuredContent):
    """
    Structured understanding of the user's question: its type, whether it is answerable from documents at all, its
    decomposition into sub-questions, key entities to search for, alternative phrasings to boost retrieval recall, and any
    ambiguities that may block a confident answer.
    """

    question_type: Literal[
        "factual", "comparative", "aggregative", "temporal", "causal", "procedural", "definitional", "counterfactual", "opinion", "out_of_scope"
    ] = Field(..., description="The cognitive type of the question, which determines whether and how documents can answer it")
    is_answerable_from_documents: bool = Field(
        ...,
        description=(
            "Whether a factual answer could in principle be derived from documents. False for counterfactual, opinion, and out_of_scope questions."
        ),
    )
    sub_questions: List[Any] = Field(
        ...,
        description=(
            "Decomposition of a compound question into independently-answerable sub-questions. For simple questions, a single-item "
            "list containing the original question."
        ),
    )
    key_entities: List[Any] = Field(..., description="Named entities, concepts, or terms the question centers on. Used to guide retrieval.")
    reformulations: List[Any] = Field(
        ...,
        description=(
            "Alternative phrasings and synonyms for the question's key terms. Improves retrieval recall when documents use different vocabulary."
        ),
    )
    ambiguities: Optional[List[Any]] = Field(
        default=None,
        description=(
            "Aspects of the question that are ambiguous and may require clarification from the user. Empty list if the question is fully specified."
        ),
    )
