"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from typing import Any, List, Literal, Optional

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class document_qa__DocumentAnswer(StructuredContent):
    """
    The final grounded answer to the user's question, with a principled status enum that distinguishes confident answers
    from every flavor of abstention.
    """

    status: Literal["answered", "partial_answer", "insufficient_evidence", "not_in_documents", "not_answerable_from_documents"] = Field(
        ..., description=("The outcome of the answer attempt. Distinguishes full answers, partial answers, and the different reasons for abstention.")
    )
    answer: str = Field(
        ...,
        description=(
            "The strictest, shortest grounded value answering the question — a bare scalar, name, yes/no, or JSON array for lists — "
            "with no prose or preamble. For any abstention status (insufficient_evidence, not_in_documents, "
            "not_answerable_from_documents), the literal string 'Not answerable'. Never empty."
        ),
    )
    explanation: Optional[str] = Field(
        default=None,
        description=(
            "Optional prose reasoning and elaboration behind the answer. For abstentions, explains why. Empty when the answer stands alone."
        ),
    )
    supporting_passages: List[Any] = Field(..., description="Every passage used to construct the answer. Empty list when nothing was cited.")
    contradictions_noted: Optional[List[Any]] = Field(
        default=None, description="Any contradictions the answer had to navigate, surfaced to the user. Empty list if none."
    )
    caveats: str = Field(
        ...,
        description=(
            "What was missing, what assumptions were made, or what the user should know about the answer's limits. For abstentions, "
            "this explains the reason."
        ),
    )
    confidence: Literal["high", "medium", "low", "none"] = Field(
        ..., description="Qualitative confidence in the answer, grounded in evidence sufficiency — not in the model's prior."
    )
