# SPDX-FileCopyrightText: © 2025 Evotis S.A.S.
# SPDX-License-Identifier: Elastic-2.0
# "Pipelex" is a trademark of Evotis S.A.S.

domain = "documents"
definition = "The domain of documents that can comprise pages, text, images, etc. in PDF or other formats"

[concept]
TextAndImagesContent = "A content that comprises text and images where the text can include local links to the images"
PageContent = "The content of a page of a document, comprising text and linked images as well as an optional screenshot of the page"
PDF = "A PDF document"

[pipe]

[pipe.extract_page_contents_from_pdf]
PipeOcr = "Extract page contents from a PDF document"
input = "native.PDF"
output = "documents.PageContent"
pdf = "pdf"
page_images = true
screenshots = false
