# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/answer_from_documents/ and cookbook.toml, as the Python snippet of methods/answer_from_documents/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
# The SDK types an input as a string, a list of strings, a content object or a list of them, or a dict, and so refuses the list of plain
# objects this sample passes, which the hosted API reads as the input's content. Until its type admits one, argument types go unchecked here.
# pyright: reportArgumentType=false
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/answer_from_documents@v0.18.0",
            inputs={
                "documents": [
                    {
                        "url": "https://huggingface.co/datasets/yubo2333/MMLongBench-Doc/resolve/main/documents/PH_2016.06.08_Economy-Final.pdf",
                    },
                ],
                "question": {
                    "text": "Among all 12 references in this report, how many are from its own research center?",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/answer_from_documents/, so that the type checker holds the page's call to the concept its "Returns" line names.
from pipelex_sdk.runs import RunResults

from generated.answer_from_documents.models import DocumentAnswer


def read_output(result: RunResults) -> DocumentAnswer:
    """The method returns one `DocumentAnswer`."""
    return DocumentAnswer.model_validate(result.main_stuff)
