# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/answer_from_documents/ and cookbook.toml, as the Python snippet of methods/answer_from_documents/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
# The SDK types an input as a string, a list of strings, a content object or a list of them, or a dict, and so refuses the list of plain
# objects this sample passes, which the hosted API reads as the input's content. Until its type admits one, argument types go unchecked here.
# pyright: reportArgumentType=false
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/answer_from_documents@v0.19.1",
            inputs={
                "documents": [
                    {
                        "url": "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/answer_from_documents/ai_system_definition_guidelines.pdf",
                    },
                ],
                "question": {
                    "text": "Our customer support team wants each new ticket to show an expected resolution time, computed as the average resolution time of past tickets in the same category. Is that tool an AI system under the AI Act?",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/answer_from_documents/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
# pipe's declared output, so the type checker fails when the page names a concept those types no longer hold.
from pipelex_sdk.runs import RunResults

from generated.answer_from_documents.models import DocumentAnswer


def read_output(result: RunResults) -> DocumentAnswer:
    """The method returns one `DocumentAnswer`."""
    return DocumentAnswer.model_validate(result.main_stuff)
