# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/extract_dpe/ and cookbook.toml, as the Python snippet of methods/extract_dpe/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/extract_dpe@v0.18.0",
            inputs={
                "document": {
                    "url": "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_dpe/dpe_single_page.pdf",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/extract_dpe/, so that the type checker holds the page's call to the concept its "Returns" line names.
from pipelex_sdk.runs import RunResults

from generated.extract_dpe.models import Dpe


def read_output(result: RunResults) -> Dpe:
    """The method returns one `Dpe`."""
    return Dpe.model_validate(result.main_stuff)
