// Generated by `make render` from methods/extract_generic/ and cookbook.toml, as the TypeScript snippet of methods/extract_generic/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/extract_generic@v0.19.1",
  inputs: {
    document: {
      url: "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_generic/fintech_article_with_text_in_images.pdf",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/extract_generic/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
// pipe's declared output, so tsc fails when the page names a concept those types no longer hold.
import { parseText } from "./generated/extract_generic/binder";

/** The items of a list output: the SDK documents the envelope {"items": [...]}, while the hosted API answers a bare list today. */
function listItems(mainStuff: unknown): unknown[] {
  if (Array.isArray(mainStuff)) {
    return mainStuff;
  }
  if (typeof mainStuff === "object" && mainStuff !== null && "items" in mainStuff && Array.isArray(mainStuff.items)) {
    return mainStuff.items;
  }
  throw new Error('expected a list output, bare or as {"items": [...]}');
}

const output = listItems(result.main_stuff).map((item) => parseText(item));
