# /// script
# requires-python = ">=3.11"
# dependencies = ["pipelex-sdk==0.12.0", "pydantic>=2.10.6"]
# ///
# Generated by `make render` from methods/extract_gantt/ and cookbook.toml, as the Python snippet of methods/extract_gantt/README.md.
# Edit those, or templates/, and render again; never edit this file by hand.
import asyncio

from pipelex_sdk.client import PipelexAPIClient


async def main() -> None:
    async with PipelexAPIClient() as client:
        result = await client.start_and_wait(
            method_ref="github.com/Pipelex/pipelex-cookbook/extract_gantt@v0.18.0",
            inputs={
                "gantt_chart_image": {
                    "url": "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/extract_gantt/gantt_tree_house.png",
                },
            },
        )
        print(result.main_stuff)


asyncio.run(main())


# Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
# generated/extract_gantt/, so that the type checker holds the page's call to the concept its "Returns" line names.
from pipelex_sdk.runs import RunResults

from generated.extract_gantt.models import GanttChart


def read_output(result: RunResults) -> GanttChart:
    """The method returns one `GanttChart`."""
    return GanttChart.model_validate(result.main_stuff)
