// Generated by `make render` from methods/answer_from_documents/ and cookbook.toml, as the TypeScript snippet of methods/answer_from_documents/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/answer_from_documents@v0.20.1",
  inputs: {
    documents: [
      {
        url: "https://raw.githubusercontent.com/Pipelex/pipelex-cookbook/main/assets/answer_from_documents/ai_system_definition_guidelines.pdf",
      },
    ],
    question: {
      text: "Our customer support team wants each new ticket to show an expected resolution time, computed as the average resolution time of past tickets in the same category. Is that tool an AI system under the AI Act?",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/answer_from_documents/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
// pipe's declared output, so tsc fails when the page names a concept those types no longer hold.
import { parseDocumentAnswer } from "./generated/answer_from_documents/binder";

const output = parseDocumentAnswer(result.main_stuff);
