// Generated by `make render` from methods/answer_from_documents/ and cookbook.toml, as the TypeScript snippet of methods/answer_from_documents/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/answer_from_documents@v0.19.1",
  inputs: {
    documents: [
      {
        url: "https://huggingface.co/datasets/yubo2333/MMLongBench-Doc/resolve/main/documents/PH_2016.06.08_Economy-Final.pdf",
      },
    ],
    question: {
      text: "Among all 12 references in this report, how many are from its own research center?",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/answer_from_documents/, as the concept the page's "Returns" line names, which loading the cookbook holds to the main
// pipe's declared output, so tsc fails when the page names a concept those types no longer hold.
import { parseDocumentAnswer } from "./generated/answer_from_documents/binder";

const output = parseDocumentAnswer(result.main_stuff);
