// Generated by `make render` from methods/research_report/ and cookbook.toml, as the TypeScript snippet of methods/research_report/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/research_report@v0.18.0",
  inputs: {
    question: {
      text: "What are the most promising approaches to improving battery energy density for electric vehicles?",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/research_report/, so that tsc holds the page's call to the concept its "Returns" line names.
import { parseFormattedReport } from "./generated/research_report/binder";

const output = parseFormattedReport(result.main_stuff);
