// Generated by `make render` from methods/blog_article_generator/ and cookbook.toml, as the TypeScript snippet of methods/blog_article_generator/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/blog_article_generator@v0.18.0",
  inputs: {
    user_prompt: {
      text: "Write a fun and engaging blog article",
      topic: "Capybara",
      audience: "Kids",
      tone: "Casual",
      length: "Long",
    },
  },
});
console.log(result.main_stuff);
