// Generated by `make render` from methods/blog_article_generator/ and cookbook.toml, as the TypeScript snippet of methods/blog_article_generator/README.md.
// Edit those, or templates/, and render again; never edit this file by hand.
import { PipelexApiClient } from "@pipelex/sdk";

const client = new PipelexApiClient({ apiKey: process.env.PIPELEX_API_KEY });
const result = await client.startAndWaitForResult({
  method_ref: "github.com/Pipelex/pipelex-cookbook/blog_article_generator@v0.18.0",
  inputs: {
    user_prompt: {
      text: "Write a fun and engaging blog article",
      topic: "Capybara",
      audience: "Kids",
      tone: "Casual",
      length: "Long",
    },
  },
});
console.log(result.main_stuff);

// Not on the page: the output read through the types `make refresh` generates from the package's .mthds files into
// generated/blog_article_generator/, so that tsc holds the page's call to the concept its "Returns" line names.
import { parseBlogArticle } from "./generated/blog_article_generator/binder";

const output = parseBlogArticle(result.main_stuff);
