name: Create release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -m 1 'version = ' pyproject.toml | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "v$VERSION"
          --repo "$GITHUB_REPOSITORY"
          --title "v$VERSION"
          --notes ""
